// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsR2naao9XikK_4jaBm7HfQtmJAC4bCo',
    appId: '1:29260081186:web:16dd516957eff844c7827b',
    messagingSenderId: '29260081186',
    projectId: 'solar-panel-211c6',
    authDomain: 'solar-panel-211c6.firebaseapp.com',
    databaseURL: 'https://solar-panel-211c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-211c6.firebasestorage.app',
    measurementId: 'G-JYDJLMJD30',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihUBkZAbimhK4f26Qv76aworFJay2oag',
    appId: '1:29260081186:ios:00eb5f7d67181e5fc7827b',
    messagingSenderId: '29260081186',
    projectId: 'solar-panel-211c6',
    databaseURL: 'https://solar-panel-211c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-211c6.firebasestorage.app',
    iosBundleId: 'com.example.renewifyLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihUBkZAbimhK4f26Qv76aworFJay2oag',
    appId: '1:29260081186:ios:00eb5f7d67181e5fc7827b',
    messagingSenderId: '29260081186',
    projectId: 'solar-panel-211c6',
    databaseURL: 'https://solar-panel-211c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-211c6.firebasestorage.app',
    iosBundleId: 'com.example.renewifyLogin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-ZTPOvbahp3KtrR2hvZwrkH8cDt4yqo',
    appId: '1:29260081186:android:199dacf2685107ebc7827b',
    messagingSenderId: '29260081186',
    projectId: 'solar-panel-211c6',
    databaseURL: 'https://solar-panel-211c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-211c6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmsR2naao9XikK_4jaBm7HfQtmJAC4bCo',
    appId: '1:29260081186:web:16dd516957eff844c7827b',
    messagingSenderId: '29260081186',
    projectId: 'solar-panel-211c6',
    authDomain: 'solar-panel-211c6.firebaseapp.com',
    databaseURL: 'https://solar-panel-211c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-panel-211c6.firebasestorage.app',
    measurementId: 'G-JYDJLMJD30',
  );

}